---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver_config:
      box: ubuntu/trusty64
  - name: centos-7
    driver_config:
      box: nrel/Centos-6.5-x86_64

suites:
  - name: default
    run_list:
      - recipe[common::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
